/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed.dashboard/index'
import { Route as AuthedDashboardConversationsIndexRouteImport } from './routes/_authed.dashboard/conversations/index'
import { Route as AuthedDashboardAgentsIndexRouteImport } from './routes/_authed.dashboard/agents/index'
import { Route as AuthedDashboardConversationsConversationIdRouteImport } from './routes/_authed.dashboard/conversations/$conversationId'
import { Route as AuthedDashboardAgentsNewRouteImport } from './routes/_authed.dashboard/agents/new'
import { Route as AuthedDashboardAgentsAgentIdRouteImport } from './routes/_authed.dashboard/agents/$agentId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardConversationsIndexRoute =
  AuthedDashboardConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardAgentsIndexRoute =
  AuthedDashboardAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardConversationsConversationIdRoute =
  AuthedDashboardConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardAgentsNewRoute =
  AuthedDashboardAgentsNewRouteImport.update({
    id: '/agents/new',
    path: '/agents/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardAgentsAgentIdRoute =
  AuthedDashboardAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/agents/$agentId': typeof AuthedDashboardAgentsAgentIdRoute
  '/dashboard/agents/new': typeof AuthedDashboardAgentsNewRoute
  '/dashboard/conversations/$conversationId': typeof AuthedDashboardConversationsConversationIdRoute
  '/dashboard/agents': typeof AuthedDashboardAgentsIndexRoute
  '/dashboard/conversations': typeof AuthedDashboardConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/agents/$agentId': typeof AuthedDashboardAgentsAgentIdRoute
  '/dashboard/agents/new': typeof AuthedDashboardAgentsNewRoute
  '/dashboard/conversations/$conversationId': typeof AuthedDashboardConversationsConversationIdRoute
  '/dashboard/agents': typeof AuthedDashboardAgentsIndexRoute
  '/dashboard/conversations': typeof AuthedDashboardConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/agents/$agentId': typeof AuthedDashboardAgentsAgentIdRoute
  '/_authed/dashboard/agents/new': typeof AuthedDashboardAgentsNewRoute
  '/_authed/dashboard/conversations/$conversationId': typeof AuthedDashboardConversationsConversationIdRoute
  '/_authed/dashboard/agents/': typeof AuthedDashboardAgentsIndexRoute
  '/_authed/dashboard/conversations/': typeof AuthedDashboardConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/new'
    | '/dashboard/conversations/$conversationId'
    | '/dashboard/agents'
    | '/dashboard/conversations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/new'
    | '/dashboard/conversations/$conversationId'
    | '/dashboard/agents'
    | '/dashboard/conversations'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/agents/$agentId'
    | '/_authed/dashboard/agents/new'
    | '/_authed/dashboard/conversations/$conversationId'
    | '/_authed/dashboard/agents/'
    | '/_authed/dashboard/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/conversations/': {
      id: '/_authed/dashboard/conversations/'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof AuthedDashboardConversationsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/agents/': {
      id: '/_authed/dashboard/agents/'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof AuthedDashboardAgentsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/conversations/$conversationId': {
      id: '/_authed/dashboard/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/dashboard/conversations/$conversationId'
      preLoaderRoute: typeof AuthedDashboardConversationsConversationIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/agents/new': {
      id: '/_authed/dashboard/agents/new'
      path: '/agents/new'
      fullPath: '/dashboard/agents/new'
      preLoaderRoute: typeof AuthedDashboardAgentsNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/agents/$agentId': {
      id: '/_authed/dashboard/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/dashboard/agents/$agentId'
      preLoaderRoute: typeof AuthedDashboardAgentsAgentIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardAgentsAgentIdRoute: typeof AuthedDashboardAgentsAgentIdRoute
  AuthedDashboardAgentsNewRoute: typeof AuthedDashboardAgentsNewRoute
  AuthedDashboardConversationsConversationIdRoute: typeof AuthedDashboardConversationsConversationIdRoute
  AuthedDashboardAgentsIndexRoute: typeof AuthedDashboardAgentsIndexRoute
  AuthedDashboardConversationsIndexRoute: typeof AuthedDashboardConversationsIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardAgentsAgentIdRoute: AuthedDashboardAgentsAgentIdRoute,
  AuthedDashboardAgentsNewRoute: AuthedDashboardAgentsNewRoute,
  AuthedDashboardConversationsConversationIdRoute:
    AuthedDashboardConversationsConversationIdRoute,
  AuthedDashboardAgentsIndexRoute: AuthedDashboardAgentsIndexRoute,
  AuthedDashboardConversationsIndexRoute:
    AuthedDashboardConversationsIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
